# Generated by Django 4.2.6 on 2025-10-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_model',
            name='post_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
