# Generated by Django 4.2.6 on 2025-10-29 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0002_career_model_post_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main banner title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=300)),
                ('occasion', models.CharField(choices=[('black_friday', 'Black Friday'), ('christmas', 'Christmas'), ('new_year', 'New Year'), ('onam', 'Onam'), ('eid', 'Eid'), ('diwali', 'Diwali'), ('easter', 'Easter'), ('valentine', "Valentine's Day"), ('independence', 'Independence Day'), ('custom', 'Custom Occasion')], default='custom', max_length=50)),
                ('custom_occasion', models.CharField(blank=True, help_text="If 'Custom Occasion' selected", max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('discount_text', models.CharField(help_text="e.g., '80% OFF'", max_length=100)),
                ('offer_description', models.CharField(help_text='Brief offer description', max_length=300)),
                ('show_timer', models.BooleanField(default=True, help_text='Show countdown timer')),
                ('end_date', models.DateTimeField(help_text='Offer expiration date & time')),
                ('background_color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #FF5733)', regex='^#([A-Fa-f0-9]{6})$')])),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #FF5733)', regex='^#([A-Fa-f0-9]{6})$')])),
                ('accent_color', models.CharField(default='#9b59b6', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #FF5733)', regex='^#([A-Fa-f0-9]{6})$')])),
                ('cta_text', models.CharField(default='Claim deal', max_length=100)),
                ('cta_link', models.URLField(help_text='Button destination URL')),
                ('additional_info', models.CharField(blank=True, help_text="Extra info (e.g., '30-day money-back guarantee')", max_length=200)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotional Banner',
                'verbose_name_plural': 'Promotional Banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
