# Generated by Django 4.2.6 on 2025-10-30 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0003_promotionalbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='vynzora_app.website'),
        ),
    ]
