# Generated by Django 4.2.6 on 2025-10-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0005_clientreview_website_technologies_website_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologies',
            name='website',
        ),
    ]
