# Generated by Django 4.2.6 on 2025-10-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0006_remove_technologies_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='website',
        ),
        migrations.RemoveField(
            model_name='clientreview',
            name='website',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='website',
        ),
    ]
