# Generated by Django 4.2.6 on 2025-10-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0007_remove_blog_website_remove_clientreview_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='main_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
