# Generated by Django 4.2.6 on 2025-10-31 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0008_website_main_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='vynzora_app.website')),
            ],
        ),
    ]
