# Generated by Django 4.2.6 on 2025-10-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0009_websitefaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='add_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
